python ../run.py \
--dataset_name ut \
--device_list 0 \
--batch_size 4 \
--train_dropout_prob 0.2 \
--base_model_path ../data/basemodel_bit.pth \
--train_learning_rate 0.00001 \
--num_boxes 5 \
--num_actions 6 \
